// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reparo.Api.Data;

#nullable disable

namespace Reparo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825170412_SeedLookupData")]
    partial class SeedLookupData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Reparo.Api.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Reparo.Shared.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FaultReportId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InterventionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FaultReportId");

                    b.HasIndex("InterventionId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Reparo.Shared.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTechnician")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Reparo.Shared.Models.FaultPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FaultPriorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nizak"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Srednji"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Visok"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kritičan"
                        });
                });

            modelBuilder.Entity("Reparo.Shared.Models.FaultReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FaultPriorityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FaultStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FaultTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReportedByEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FaultPriorityId");

                    b.HasIndex("FaultStatusId");

                    b.HasIndex("FaultTypeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ReportedByEmployeeId");

                    b.ToTable("FaultReports");
                });

            modelBuilder.Entity("Reparo.Shared.Models.FaultStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FaultStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Zaprimljeno"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pregledano"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dodijeljeno"
                        },
                        new
                        {
                            Id = 4,
                            Name = "U radu"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Riješeno"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Zatvoreno"
                        });
                });

            modelBuilder.Entity("Reparo.Shared.Models.FaultType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FaultTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elektrika"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Voda"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Grijanje"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mreža"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Građevinski radovi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ostalo"
                        });
                });

            modelBuilder.Entity("Reparo.Shared.Models.Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InterventionStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkAssignmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InterventionStatusId");

                    b.HasIndex("WorkAssignmentId");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("Reparo.Shared.Models.InterventionMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterventionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialUnitId");

                    b.ToTable("InterventionMaterials");
                });

            modelBuilder.Entity("Reparo.Shared.Models.InterventionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InterventionStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Planirana"
                        },
                        new
                        {
                            Id = 2,
                            Name = "U tijeku"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Završena"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Neuspješna"
                        });
                });

            modelBuilder.Entity("Reparo.Shared.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationTypeId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Reparo.Shared.Models.LocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LocationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Upravna zgrada"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Škola"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Zdravstvena ustanova"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Skladište"
                        });
                });

            modelBuilder.Entity("Reparo.Shared.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Reparo.Shared.Models.MaterialUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MaterialUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Komad"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Metar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Litra"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Paket"
                        });
                });

            modelBuilder.Entity("Reparo.Shared.Models.WorkAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FaultReportId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FaultReportId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("WorkAssignments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Reparo.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Reparo.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reparo.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Reparo.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reparo.Api.Models.AppUser", b =>
                {
                    b.HasOne("Reparo.Shared.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Reparo.Shared.Models.Attachment", b =>
                {
                    b.HasOne("Reparo.Shared.Models.FaultReport", "FaultReport")
                        .WithMany("Attachments")
                        .HasForeignKey("FaultReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reparo.Shared.Models.Intervention", "Intervention")
                        .WithMany("Attachments")
                        .HasForeignKey("InterventionId");

                    b.Navigation("FaultReport");

                    b.Navigation("Intervention");
                });

            modelBuilder.Entity("Reparo.Shared.Models.Employee", b =>
                {
                    b.HasOne("Reparo.Shared.Models.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Reparo.Shared.Models.FaultReport", b =>
                {
                    b.HasOne("Reparo.Shared.Models.FaultPriority", "FaultPriority")
                        .WithMany()
                        .HasForeignKey("FaultPriorityId");

                    b.HasOne("Reparo.Shared.Models.FaultStatus", "FaultStatus")
                        .WithMany()
                        .HasForeignKey("FaultStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reparo.Shared.Models.FaultType", "FaultType")
                        .WithMany()
                        .HasForeignKey("FaultTypeId");

                    b.HasOne("Reparo.Shared.Models.Location", "Location")
                        .WithMany("FaultReports")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reparo.Shared.Models.Employee", "ReportedByEmployee")
                        .WithMany("ReportedFaults")
                        .HasForeignKey("ReportedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FaultPriority");

                    b.Navigation("FaultStatus");

                    b.Navigation("FaultType");

                    b.Navigation("Location");

                    b.Navigation("ReportedByEmployee");
                });

            modelBuilder.Entity("Reparo.Shared.Models.Intervention", b =>
                {
                    b.HasOne("Reparo.Shared.Models.InterventionStatus", "InterventionStatus")
                        .WithMany()
                        .HasForeignKey("InterventionStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reparo.Shared.Models.WorkAssignment", "WorkAssignment")
                        .WithMany("Interventions")
                        .HasForeignKey("WorkAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterventionStatus");

                    b.Navigation("WorkAssignment");
                });

            modelBuilder.Entity("Reparo.Shared.Models.InterventionMaterial", b =>
                {
                    b.HasOne("Reparo.Shared.Models.Intervention", "Intervention")
                        .WithMany("Materials")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reparo.Shared.Models.Material", "Material")
                        .WithMany("InterventionMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reparo.Shared.Models.MaterialUnit", "MaterialUnit")
                        .WithMany()
                        .HasForeignKey("MaterialUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intervention");

                    b.Navigation("Material");

                    b.Navigation("MaterialUnit");
                });

            modelBuilder.Entity("Reparo.Shared.Models.Location", b =>
                {
                    b.HasOne("Reparo.Shared.Models.LocationType", "LocationType")
                        .WithMany()
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationType");
                });

            modelBuilder.Entity("Reparo.Shared.Models.WorkAssignment", b =>
                {
                    b.HasOne("Reparo.Shared.Models.FaultReport", "FaultReport")
                        .WithMany("Assignments")
                        .HasForeignKey("FaultReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reparo.Shared.Models.Employee", "Technician")
                        .WithMany("Assignments")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FaultReport");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Reparo.Shared.Models.Employee", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ReportedFaults");
                });

            modelBuilder.Entity("Reparo.Shared.Models.FaultReport", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Reparo.Shared.Models.Intervention", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("Reparo.Shared.Models.Location", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("FaultReports");
                });

            modelBuilder.Entity("Reparo.Shared.Models.Material", b =>
                {
                    b.Navigation("InterventionMaterials");
                });

            modelBuilder.Entity("Reparo.Shared.Models.WorkAssignment", b =>
                {
                    b.Navigation("Interventions");
                });
#pragma warning restore 612, 618
        }
    }
}
